### ISSUE TITLE
Proxy settings not used

### ISSUE THREAD

**Issue by johwech** [OtterBrowser/otter-browser#1423]
Setting up a proxy for all connections.
Even if the proxy is not running, I can still browse normally.

I'd like to use otter as a browser for I2P because it still allows proxy settings independent from the global windows settings. But for privacy here it is important that all connections are routed through the I2P proxy.

> Version:
> 	Main Number         0.9.91
> 	Weekly Number       -
> 	Context             -RC1
> 	Web Backend         WebKit Backend 602.1
> 
> Environment:
> 	System Name                   Windows 10 (10.0)
> 	Build ABI                     x86_64-little_endian-llp64
> 	Build CPU Architecture        x86_64
> 	Current CPU Architecture      x86_64
> 	Build Qt Version              5.9.1
> 	Current Qt Version            5.9.1
> 	Locale                        en_GB

**Comment by RJVB** [comment]
This is still the case. In fact, "system proxy" doesn't pick up the one I have configured either.

Easy to check, too: I use privoxy so I can check if it's being used by going to `http://config.privoxy.org`

**Comment by ChampionCynthia** [comment]
Ditto. Both manual and system configuration.

**Comment by pvtitale** [comment]
I have the same behavior with 0.9.94-dev with web backend: Blink 49.0.2623.111

**Comment by Emdek** [comment]
Please let me know if there is anything left to fix (note that right now these fixes landed only in the master branch).

**Comment by RJVB** [comment]
It works now, but proxy changes are still not effective immediately. I had to restart the browser in order for it to use the proxy.

**Comment by Emdek** [comment]
@RJVB, what exact change was that?
Global or per website, changing existing definition, adding new one or switching to another (manual, automatic, none or system)?

**Comment by Emdek** [comment]
@RJVB, uhm, you could try to limit caching factor by using private mode, but I doubt that it's the problem.
I can also try to prepare some sort of debugging patch (which prints out proxy used by every request), that could help in determining what exactly was used.

Issues with reflecting system configuration changes are different beast, I'm not sure if this is still relevant, but was an issue in the past:
https://stackoverflow.com/questions/4159964/qnetworkproxyfactorysystemproxyforquery-is-not-reflecting-changes-to-system

**Comment by Emdek** [comment]
@RJVB, uhm, that is odd, should work the same way both ways or none.
Anyway, here is patch for master for printing out which proxy was used for given request:
```diff
diff --git a/src/core/NetworkProxyFactory.cpp b/src/core/NetworkProxyFactory.cpp
index 3cc8f073..8028a77d 100644
--- a/src/core/NetworkProxyFactory.cpp
+++ b/src/core/NetworkProxyFactory.cpp
@@ -88,9 +88,11 @@ void NetworkProxyFactory::setProxy(const QString &identifier)
 
 QList<QNetworkProxy> NetworkProxyFactory::queryProxy(const QNetworkProxyQuery &query)
 {
+	qDebug() << "request for" << query.url().toString() << ':';
 	switch (m_definition.type)
 	{
 		case ProxyDefinition::SystemProxy:
+			qDebug() << "system proxy";
 			return QNetworkProxyFactory::systemProxyForQuery(query);
 
 		case ProxyDefinition::ManualProxy:
@@ -106,17 +108,20 @@ QList<QNetworkProxy> NetworkProxyFactory::queryProxy(const QNetworkProxyQuery &q
 
 						if (!address.isNull() && subnet.second != -1 && address.isInSubnet(subnet))
 						{
+							qDebug() << "no proxy (exception)";
 							return m_proxies[-1];
 						}
 					}
 					else if (host.contains(m_definition.exceptions.at(i), Qt::CaseInsensitive))
 					{
+						qDebug() << "no proxy (exception)";
 						return m_proxies[-1];
 					}
 				}
 
 				if (m_proxies.contains(ProxyDefinition::SocksProtocol))
 				{
+					qDebug() << "SOCKS proxy";
 					return m_proxies[ProxyDefinition::SocksProtocol];
 				}
 
@@ -124,19 +129,23 @@ QList<QNetworkProxy> NetworkProxyFactory::queryProxy(const QNetworkProxyQuery &q
 
 				if (protocol == QLatin1String("http") && m_proxies.contains(ProxyDefinition::HttpProtocol))
 				{
+					qDebug() << "HTTP proxy";
 					return m_proxies[ProxyDefinition::HttpProtocol];
 				}
 
 				if (protocol == QLatin1String("https") && m_proxies.contains(ProxyDefinition::HttpsProtocol))
 				{
+					qDebug() << "HTTPS proxy";
 					return m_proxies[ProxyDefinition::HttpsProtocol];
 				}
 
 				if (protocol == QLatin1String("ftp") && m_proxies.contains(ProxyDefinition::FtpProtocol))
 				{
+					qDebug() << "FTP proxy";
 					return m_proxies[ProxyDefinition::FtpProtocol];
 				}
 
+				qDebug() << "no proxy (fallback)";
 				return m_proxies[-1];
 			}
 
@@ -144,14 +153,17 @@ QList<QNetworkProxy> NetworkProxyFactory::queryProxy(const QNetworkProxyQuery &q
 		case ProxyDefinition::AutomaticProxy:
 			if (m_automaticProxy && m_automaticProxy->isValid())
 			{
+				qDebug() << "automatic proxy";
 				return m_automaticProxy->getProxy(query.url().toString(), query.peerHostName()).toList();
 			}
 
+			qDebug() << "system proxy (fallback)";
 			return QNetworkProxyFactory::systemProxyForQuery(query);
 		default:
 			break;
 	}
 
+	qDebug() << "no proxy (final fallback)";
 	return m_proxies[-1];
 }
 
```

I've added that link just in case, if someone would experience that kind of issues. ;-)

**Comment by Emdek** [comment]
BTW, I think that it could be a good idea to add an option to specify what should be the fallback, system or nothing.
