### ISSUE TITLE
[Bug] Otter crashes on startup

### ISSUE THREAD

**Issue by BlackLotus** [OtterBrowser/otter-browser#1681]
Running Arch Linux Otter version 1.0.02-2.
Installed some time ago.
Here is the gdb backtrace
```
(gdb) backtrace 
#0  0x00006831a012b0c7 in QIODevice::errorString() const () at /usr/lib/libQt5Core.so.5
#1  0x0000007e1ce7dee1 in Otter::AdblockContentFiltersProfile::handleJobFinished(bool) ()
#2  0x00006831a023375b in  () at /usr/lib/libQt5Core.so.5
#3  0x0000007e1ce36790 in Otter::Job::jobFinished(bool) ()
#4  0x00006831a023375b in  () at /usr/lib/libQt5Core.so.5
#5  0x00006831a05514c5 in  () at /usr/lib/libQt5Network.so.5
#6  0x00006831a02294ff in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#7  0x00006831a404cd62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00006831a01fc3aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#9  0x00006831a01ff4a9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#10 0x00006831a02559a4 in  () at /usr/lib/libQt5Core.so.5
#11 0x000068319e11610c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x000068319e169b99 in  () at /usr/lib/libglib-2.0.so.0
#13 0x000068319e113871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00006831a0254fd6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#15 0x00006831a01fad1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#16 0x00006831a0203284 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#17 0x0000007e1ce314bf in main ()
```
Don't know what caused the crash. Starting a fresh session prevents it from crashing.

**Comment by Emdek** [comment]
@BlackLotus, I'm pretty sure that this one is already fixed in both master and 1.0.xx branch, any chance that you could try building from source?

**Comment by BlackLotus** [comment]
Sorry for the delay.
Seems to not crash with master (should have tested that myself before posting the bug report, but since there was a long time since I last used otter and it still crashed with my profile even after the new release I thought it would be futile)
Anyway sorry for the noise.
